wanted_words: 'non_trigger,trigger'
data_path: 'train_dataset'
train_res: 'train_res/ds_tc_resnet/'
split_data: 0

clip_duration_ms: 1000
background_volume: 0.1
background_frequency: 0.8

training_steps: '2,2,2,2,2,2'
learning_rate: '0.01,0.005,0.002,0.001,0.0005,0.0002'
lr_schedule: 'linear'
batch_size: 1
eval_step_interval: 1

mel_upper_edge_hertz: 7600.0
mel_lower_edge_hertz: 20.0
window_size_ms: 30.0
window_stride_ms: 10.0
mel_num_bins: 80
dct_num_features: 40

use_spec_augment: 1
time_masks_number: 2
time_mask_max_size: 25
frequency_masks_number: 2
frequency_mask_max_size: 7
pick_deterministically: 1