FROM nvcr.io/nvidia/tensorflow:22.01-tf2-py3
RUN mkdir /workspace
WORKDIR /workspace


RUN apt-get update
COPY requirements-gpu.txt requirements-gpu.txt
RUN pip install -r requirements-gpu.txt --no-cache-dir
RUN rm -f requirements-gpu.txt

RUN mkdir /workspace/keyword-spotting-train
WORKDIR /workspace/keyword-spotting-train

CMD [ "/bin/bash" ]